name: Build and Deploy
on:
    pull_request:
    push:
      branches:
        - master

jobs:

  build:
    name: Package App
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: peterskipper/dashboard_cd
          tag_with_sha: true

  deploy:
        name: Deploy with Terraform
        needs: build
        runs-on: ubuntu-latest
        if:
            github.event_name == 'pull_request' || (github.event_name == 'push' && github.branch == 'master')
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1

        - name: Terraform Init
          run: terraform init

        - name: Terraform Format
          run: terraform fmt -check

        - name: Terraform Validate
          run: terraform validate -no-color

        - name: Terraform Plan
          run: terraform plan -var='docker_image_tag=sha-${GITHUB_SHA:0:7}'

        - name: Terraform Apply
          run: terraform apply -var="docker_image_tag=sha-${GITHUB_SHA:0:7}" -auto-approve -input=false
